apiVersion: deployment.jorisjonkers.dev/v2
kind: Deployment
metadata:
  name: stalwart-provisioner
spec:
  namespace: mail-system
  workloads:
    - name: stalwart-provisioner
      kind: job
      image:
        alias: stalwart-provisioner
      health:
        timeoutClass: job
